### PR TITLE
Fix/query params

### LINKED ISSUE #41: String params not wrapped in quotes
**Describe the bug**

When using parameters in a query, I'm getting this error:

> Unable to parse value of "$baseLanguage=us-en". Please quote string values.

I think this needs to be fixed in https://github.com/sanity-io/swift-sanity/blob/f402555b9a1c9ef808feb29d5dc910653b0f6841/Sources/Sanity/SanityClient.swift#L203, parameter values need to be escaped appropriately.

In my code, I've worked around this with:

```swift
sanityClient.query(type, query: query, params: params.mapValues({ "\"\($0)\""})).fetch { result in
```

I've got a wrapper to add `async` support to querying.

**To Reproduce**

Make a query with a named parameter with a string value.

**Expected behavior**

My query works.

**Which versions of Sanity are you using?**

- 0.18.0 of sanity swift
- .v20250219 of the API

**What operating system are you using?**

iOS

**Which versions of Node.js / npm are you running?**

n/a

### PR DESCRIPTION
**Pull request by sgulseth**
### Description

We were not properly encoding strings when passed as parameters. This fixes it.

Fixes #41 

### Testing

Added

### CODE REVIEW

File: Sources/Sanity/SanityClient.swift [hunk 1]
```diff
@@ -200,11 +200,19 @@ public class SanityClient {
                 params
                     .sorted { $0.key < $1.key }
                     .forEach { param in
-                        let queryItem = URLQueryItem(name: "$\(param.key)", value: String(describing: param.value))
+                        let queryItem = URLQueryItem(name: "$\(param.key)", value: Self.jsonEncode(param.value))
```
Comment (dcilke) [inline Sources/Sanity/SanityClient.swift:203]: 🤔 will URLQueryItem url encode the value? Something like
```
public extension String {   
    func urlEncoded() -> String? {
        addingPercentEncoding(withAllowedCharacters: .urlPathAllowed)?
            .replacingOccurrences(of: "&", with: "%26")
    }
}
```

File: Sources/Sanity/SanityClient.swift [hunk 2]
```diff
@@ -200,11 +200,19 @@ public class SanityClient {
...
                     }
             }
 
+            static func jsonEncode(_ value: Any) -> String {
+                guard let data = try? JSONSerialization.data(withJSONObject: value, options: .fragmentsAllowed),
+                      let json = String(data: data, encoding: .utf8) else {
+                    fatalError("Unsupported GROQ parameter type: \(type(of: value)). Parameters must be JSON-compatible (String, Number, Bool, Array, Dictionary, or NSNull).")
+                }
+                return json
+            }
```
Comment (dcilke) [inline Sources/Sanity/SanityClient.swift:214]: You could extend string (maybe it complicates the error message...)

**Review by dcilke — APPROVED** [review]

File: Sources/Sanity/SanityClient.swift (hunk 2 above)
Comment (sgulseth) [reply Sources/Sanity/SanityClient.swift:214]: WDYM? 🤔

File: Sources/Sanity/SanityClient.swift (hunk 1 above)
Comment (sgulseth) [reply Sources/Sanity/SanityClient.swift:203]: yeah, it's encoded by urlcomponents where it's used.

playground https://swiftfiddle.com/yhrb6mqj6ngvlcbq764f5ovlpu

File: Sources/Sanity/SanityClient.swift (hunk 2 above)
Comment (dcilke) [reply Sources/Sanity/SanityClient.swift:214]: I was thinking if there was a way to reuse the "serialize and throw" logic.
